export const OWNER_ACTIONS = {
  // Authentication
  REGISTER: 'REGISTER_OWNER',
  LOGIN: 'LOGIN_OWNER',
  LOGOUT: 'LOGOUT_OWNER',
  
  // Profile Management
  UPDATE_PROFILE: 'UPDATE_OWNER_PROFILE',
  VIEW_PROFILE: 'VIEW_OWNER_PROFILE',
} 